import os
Import('*')

# code specific to this app
projectName='app'
requiredLibraries = ['module1']

# common code that should go into an application builder...
sampleApplicationEnv = env.Clone()
sampleApplicationEnv.Append(LIBS=[lib for lib in requiredLibraries])
sampleApplicationEnv.Append(LIBPATH=[os.path.join(buildDir, lib) for lib in requiredLibraries])
#print sampleApplicationEnv.Dump('LIBS') # This is the syntax necessary to look at SCons environment variables
sampleApplication = sampleApplicationEnv.Program(projectName, Glob('*.cpp'))

Default(sampleApplication)
Default(sampleApplicationEnv.Install(binDir, sampleApplication))
