import os
Import('*')

projectName='app'
sampleApplicationEnv = env.Clone()
sampleApplicationEnv.Append(LIBS=['lib'])
sampleApplicationEnv.Append(LIBPATH=[os.path.join(buildDir, 'lib')])
#print sampleApplicationEnv.Dump('LIBPATH') # This is the syntax necessary to look at the SCons environment 

sampleApplication = sampleApplicationEnv.Program(projectName, Glob('*.cpp'))
#Depends(sampleApplication, libs)

Default(sampleApplication)
Default(sampleApplicationEnv.Install(binDir, sampleApplication))
#sampleApplicationEnv.Install(binDir, 'SampleLibrary.dll')
#Alias('all', sampleApplicationEnv.Install(binDir, sampleApplication))
#Default(Alias('all'))
#sampleApplicationEnv.Install(binDir, sampleApplication)
